# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: uniswap-v4-indexer
storage:
  postgres: true
  clickhouse: false
contracts:
  - name: PoolManager
    events:
      - event: Approval(address indexed owner, address indexed spender, uint256 indexed id, uint256 amount)
      - event: Donate(bytes32 indexed id, address indexed sender, uint256 amount0, uint256 amount1)
      - event: Initialize(bytes32 indexed id, address indexed currency0, address indexed currency1, uint24 fee, int24 tickSpacing, address hooks, uint160 sqrtPriceX96, int24 tick)
      - event: ModifyLiquidity(bytes32 indexed id, address indexed sender, int24 tickLower, int24 tickUpper, int256 liquidityDelta, bytes32 salt)
        field_selection: # Additional fields available to index to augment data
          transaction_fields:
            - "hash"
            - "from"
      - event: OperatorSet(address indexed owner, address indexed operator, bool approved)
      - event: OwnershipTransferred(address indexed user, address indexed newOwner)
      - event: ProtocolFeeControllerUpdated(address indexed protocolFeeController)
      - event: ProtocolFeeUpdated(bytes32 indexed id, uint24 protocolFee)
      - event: Swap(bytes32 indexed id, address indexed sender, int128 amount0, int128 amount1, uint160 sqrtPriceX96, uint128 liquidity, int24 tick, uint24 fee)
        field_selection: # Additional fields available to index to augment data
          transaction_fields:
            - "hash"
            - "from"
      - event: Transfer(address caller, address indexed from, address indexed to, uint256 indexed id, uint256 amount)
  - name: PositionManager
    events:
      - event: Subscription(uint256 indexed tokenId, address indexed subscriber)
        field_selection:
          transaction_fields:
            - "hash"
            - "from"
      - event: Transfer(address indexed from, address indexed to, uint256 indexed id)
        field_selection:
          transaction_fields:
            - "hash"
            - "from"
      - event: Unsubscription(uint256 indexed tokenId, address indexed subscriber)
        field_selection:
          transaction_fields:
            - "hash"
            - "from"
chains:
  - id: 1
    start_block: 0
    contracts:
      - name: PositionManager
        address:
          - 0xbD216513d74C8cf14cf4747E6AaA6420FF64ee9e
      - name: PoolManager
        address:
          - "0x000000000004444c5dc75cB358380D2e3dE08A90"
  - id: 56
    start_block: 0
    contracts:
      - name: PositionManager
        address:
          - 0x7a4a5c919ae2541aed11041a1aeee68f1287f95b
      - name: PoolManager
        address:
          - 0x28e2ea090877bf75740558f6bfb36a5ffee9e9df
  - id: 4663
    start_block: 9070
    contracts:
      - name: PositionManager
        address:
          - 0x58daec3116aae6d93017baaea7749052e8a04fa7
      - name: PoolManager
        address:
          - 0x8366a39cc670b4001a1121b8f6a443a643e40951
